[config]
huso = "Europe/Madrid"
habitaculo = "cocina"
carpeta_logs = "logs"
aislamiento_termico = 0.7

[lux]
lux_max_cenit = 5000
lux_artificial = 500
lux_noche_farolas = 10
grados_lux_directa = 60

[modos]
climatizador = "off"
humidificador = "off"
luz = "off"
ventana = "off"
persiana = "off"

[ids]
controlador = "contr-d0sQ5oifze"
temperatura = "temp-6X6jGn2434"
humedad = "hum-HJo8QenvfZ"
luz_resultante = "lux-WCWEeKo6We"
ventana = "vent-TbNe2XYxd9"
luz = "luz-fb9t8M06Xd"
puerta = "puer-UhXIo2ilMk"
climatizador = "clim-OXVwejXTxv"
humidificador = "humid-PCCOYHMYcZ"
presencia = "prese-ejZCsREI0Y"
persiana = "persi-IksNLbRbwD"

[ventanas.ventana1]
orientacion = 180
area = 120

[ventanas.ventana2]
orientacion = 90
area = 80

[config_controlador.climatizador]
temperatura_min = 18
temperatura_max = 30

[config_controlador.humidificador]
humedad_min = 40
humedad_max = 70

[config_controlador.persiana]
velocidad = 1
