[config]
huso = "Europe/Madrid"
habitaculo = "cocina"
carpeta_logs = "logs"

[lux]
lux_max_cenit = 5000
lux_artificial = 500
lux_noche_farolas = 10
grados_lux_directa = 60

[ventanas]

[ventanas.ventana1]
orientacion = 180
area = 120

[ventanas.ventana2]
orientacion = 90
area = 80

[config_controlador]

[config_controlador.climatizador]   
temperatura_min = 20
temperatura_max = 30

[config_controlador.ventana]
continuar = 1

[config_controlador.humidificador]
humedad_min = 40
humedad_max = 60

[config_controlador.persiana]
velocidad = 1