[valores_magnitudes]
temperatura = 23.07
humedad = 49.36
luz_ambiente = 1969.48
luz_resultante = 1969.48
presencia = false

[actuadores.persiana]
en_funcionamiento = true
estado = 0.2

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = false
estado = 0.4

[actuadores.ventana]
en_funcionamiento = false
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = false
estado = 23.0

[actuadores.humidificador]
en_funcionamiento = false
estado = 50.0
