[valores_magnitudes]
temperatura = 23.66
humedad = 40.94
lux = 413.86
presencia = 0

[actuadores.persiana]
en_funcionamiento = true
estado = 0.6

[actuadores.luz]
en_funcionamiento = false
estado = 500.0

[actuadores.puerta]
en_funcionamiento = true
estado = 0.4

[actuadores.ventana]
en_funcionamiento = true
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = true
estado = 22.0
