[valores_magnitudes]
temperatura = 22.13
humedad = 45.64
luz_ambiente = 2.89
luz_resultante = 2.89
presencia = false

[actuadores.persiana]
en_funcionamiento = true
estado = 1.0

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = false
estado = 0.4

[actuadores.ventana]
en_funcionamiento = false
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = false
estado = 22.0

[actuadores.humidificador]
en_funcionamiento = false
estado = 50.0
