[valores_magnitudes]
temperatura = 0
humedad = 0
luz_ambiente = 0
luz_resultante = 0
presencia = false

[actuadores.persiana]
en_funcionamiento = true
estado = 0

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = false
estado = 0

[actuadores.ventana]
en_funcionamiento = false
estado = 0

[actuadores.climatizador]
en_funcionamiento = false
estado = 0

[actuadores.humidificador]
en_funcionamiento = false
estado = 0
