[valores_magnitudes]
temperatura = 26.55
humedad = 43.41
luz_ambiente = 2697.41
luz_resultante = 2697.41
presencia = true

[actuadores.persiana]
en_funcionamiento = true
estado = 0.9

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = false
estado = 0.4

[actuadores.ventana]
en_funcionamiento = false
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = false
estado = 22

[actuadores.humidificador]
en_funcionamiento = false
estado = 50.0
