[valores_magnitudes]
temperatura = 23.49
humedad = 39.73
luz_ambiente = 425.07
luz_resultante = 425.07
presencia = false

[actuadores.persiana]
en_funcionamiento = true
estado = 0.7

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = false
estado = 0.4

[actuadores.ventana]
en_funcionamiento = false
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = true
estado = 23.0

[actuadores.humidificador]
en_funcionamiento = true
estado = 50.0
