[valores_magnitudes]
temperatura = 23.55
humedad = 46.67
luz_ambiente = 5
luz_resultante = 5
presencia = false

[actuadores.persiana]
en_funcionamiento = true
estado = 0.1

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = true
estado = 0.4

[actuadores.ventana]
en_funcionamiento = true
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = true
estado = 22.0

[actuadores.humidificador]
en_funcionamiento = false
estado = 50
