[valores_magnitudes]
temperatura = 30.39
humedad = 48.83
luz_ambiente = 2991.3
luz_resultante = 0.0
presencia = false

[actuadores.persiana]
en_funcionamiento = true
estado = 0.5

[actuadores.luz]
en_funcionamiento = false
estado = 0

[actuadores.puerta]
en_funcionamiento = true
estado = 0.4

[actuadores.ventana]
en_funcionamiento = true
estado = 0.2

[actuadores.climatizador]
en_funcionamiento = true
estado = 22.0

[actuadores.humidificador]
en_funcionamiento = false
estado = 50
