[config]
huso = ""
habitaculo = ""
carpeta_logs = ""
aislamiento_termico = 0

[es]
url = ""

[lux]
lux_max_cenit = 0
lux_artificial = 0
lux_noche_farolas = 0
grados_lux_directa = 0

[modos]
climatizador = ""
humidificador = ""
luz = ""
ventana = ""
persiana = ""

[ventanas.ventana1]
orientacion = 0
area = 0

[ventanas.ventana2]
orientacion = 0
area = 0

[config_controlador.climatizador]
temperatura_min = 0
temperatura_max = 0

[config_controlador.humidificador]
humedad_min = 0
humedad_max = 0

[config_controlador.persiana]
velocidad = 0
